name: CI – Build & Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo klónozása
      uses: actions/checkout@v3

    - name: Node.js telepítése
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Függőségek telepítése (frontend + backend)
      run: |
        cd backend && npm install && cd ..
        cd frontend && npm install

    - name: Build check (ha van)
      run: |
        cd frontend && npm run build || echo "build figyelmeztetés"

    - name: Kód lefuttatása (csak példa)
      run: echo "CI kész – nincs hiba"
